//=require '../libs/jquery/dist/jquery.js'
//=require '../libs/slick-carousel/slick/slick.js'
//=require '../libs/fancybox/dist/jquery.fancybox.js'

//=require '../libs/jquery-ui/ui/version.js'
//=require '../libs/jquery-ui/ui/safe-active-element.js'
//=require '../libs/jquery-ui/ui/escape-selector.js'
//=require '../libs/jquery-ui/ui/form.js'
//=require '../libs/jquery-ui/ui/widget.js'
//=require '../libs/jquery-ui/ui/position.js'
//=require '../libs/jquery-ui/ui/form-reset-mixin.js'
//=require '../libs/jquery-ui/ui/keycode.js'
//=require '../libs/jquery-ui/ui/labels.js'
//=require '../libs/jquery-ui/ui/unique-id.js'
//=require '../libs/jquery-ui/ui/widgets/menu.js'
//=require '../libs/jquery-ui/ui/widgets/selectmenu.js'